insert into filmes (name, gender, yearr, diretores_id) values ('Come Undone (Presque Rien)', 'Drama|Romance', '2020-10-31', 1);
insert into filmes (name, gender, yearr, diretores_id) values ('SpongeBob Movie: Sponge Out of Water, The', 'Adventure|Animation|Children|Comedy', '2015-02-06', 12);
insert into filmes (name, gender, yearr, diretores_id) values ('Walk Softly, Stranger', 'Crime|Drama|Film-Noir|Romance', '2017-04-03', 62);
insert into filmes (name, gender, yearr, diretores_id) values ('Highway to Hell', 'Action|Comedy|Fantasy|Horror', '2013-11-07', 94);
insert into filmes (name, gender, yearr, diretores_id) values ('XX/XY', 'Drama|Romance', '2018-05-21', 92);
insert into filmes (name, gender, yearr, diretores_id) values ('Rehearsals for Extinct Anatomies', 'Animation', '2015-06-13', 98);
insert into filmes (name, gender, yearr, diretores_id) values ('Big Momma''s House', 'Comedy', '2017-11-09', 6);
insert into filmes (name, gender, yearr, diretores_id) values ('Three Burials of Melquiades Estrada, The', 'Adventure|Crime|Drama', '2015-02-22', 63);
insert into filmes (name, gender, yearr, diretores_id) values ('Footlight Parade', 'Comedy|Musical|Romance', '2019-11-17', 9);
insert into filmes (name, gender, yearr, diretores_id) values ('Surviving Christmas', 'Comedy', '2011-01-21', 98);
insert into filmes (name, gender, yearr, diretores_id) values ('Bigger Than the Sky', 'Comedy|Drama|Romance', '2019-08-28', 61);
insert into filmes (name, gender, yearr, diretores_id) values ('Sound of Redemption: The Frank Morgan Story', 'Documentary|Drama|Musical', '2019-03-24', 1);
insert into filmes (name, gender, yearr, diretores_id) values ('Welcome to Dongmakgol', 'Comedy|Drama|War', '2018-04-20', 56);
insert into filmes (name, gender, yearr, diretores_id) values ('Mama', 'Horror', '2017-11-03', 48);
insert into filmes (name, gender, yearr, diretores_id) values ('Luzhin Defence, The', 'Drama|Romance', '2020-12-20', 13);
insert into filmes (name, gender, yearr, diretores_id) values ('The Returned', 'Drama|Horror|Thriller', '2015-08-28', 52);
insert into filmes (name, gender, yearr, diretores_id) values ('The Horribly Slow Murderer with the Extremely Inefficient Weapon', 'Comedy|Horror', '2016-05-29', 99);
insert into filmes (name, gender, yearr, diretores_id) values ('Dead Genesis', 'Horror', '2011-12-06', 54);
insert into filmes (name, gender, yearr, diretores_id) values ('Van Helsing', 'Action|Adventure|Fantasy|Horror', '2011-09-12', 9);
insert into filmes (name, gender, yearr, diretores_id) values ('Ledge, The', 'Drama|Thriller', '2013-01-28', 44);
insert into filmes (name, gender, yearr, diretores_id) values ('Hamster Factor and Other Tales of Twelve Monkeys, The', 'Documentary', '2022-07-17', 94);
insert into filmes (name, gender, yearr, diretores_id) values ('I Feel Sleepy', 'Comedy', '2016-02-07', 2);
insert into filmes (name, gender, yearr, diretores_id) values ('In the Mood For Love (Fa yeung nin wa)', 'Drama|Romance', '2012-12-08', 65);
insert into filmes (name, gender, yearr, diretores_id) values ('Iceman Cometh, The', 'Drama', '2012-04-20', 77);
insert into filmes (name, gender, yearr, diretores_id) values ('Strictly Sexual', 'Comedy|Drama|Romance', '2022-03-31', 34);
insert into filmes (name, gender, yearr, diretores_id) values ('India: Matri Bhumi', 'Documentary|Drama', '2014-03-05', 33);
insert into filmes (name, gender, yearr, diretores_id) values ('Chaser, The (Chugyeogja)', 'Crime|Drama|Thriller', '2017-08-08', 3);
insert into filmes (name, gender, yearr, diretores_id) values ('Revolutionary Road', 'Drama|Romance', '2012-03-15', 14);
insert into filmes (name, gender, yearr, diretores_id) values ('Film Noir: Bringing Darkness to Light', 'Documentary', '2016-05-25', 57);
insert into filmes (name, gender, yearr, diretores_id) values ('Charming Mass Suicide, A (Hurmaava joukkoitsemurha)', 'Comedy', '2016-06-03', 64);
insert into filmes (name, gender, yearr, diretores_id) values ('Sweet Liberty', 'Comedy', '2012-06-15', 45);
insert into filmes (name, gender, yearr, diretores_id) values ('Last Mountain, The', 'Documentary', '2012-01-13', 100);
insert into filmes (name, gender, yearr, diretores_id) values ('Irina Palm', 'Drama', '2022-04-13', 12);
insert into filmes (name, gender, yearr, diretores_id) values ('Iria: Zeiram the Animation ', 'Action|Animation|Horror|Sci-Fi|Thriller', '2013-02-03', 45);
insert into filmes (name, gender, yearr, diretores_id) values ('Zero Day', 'Drama', '2016-09-12', 28);
insert into filmes (name, gender, yearr, diretores_id) values ('Hidden Agenda', 'Action|Mystery|Thriller', '2013-04-01', 68);
insert into filmes (name, gender, yearr, diretores_id) values ('Knife in the Water (Nóz w wodzie)', 'Drama', '2011-12-20', 28);
insert into filmes (name, gender, yearr, diretores_id) values ('12 Years a Slave', 'Drama', '2014-04-16', 74);
insert into filmes (name, gender, yearr, diretores_id) values ('Avengers, The', 'Action|Adventure', '2011-05-31', 92);
insert into filmes (name, gender, yearr, diretores_id) values ('Unholy Rollers, The', 'Action|Comedy|Drama', '2019-05-22', 10);
insert into filmes (name, gender, yearr, diretores_id) values ('Alibi, The (Lies and Alibis)', 'Comedy|Drama|Romance', '2014-02-11', 90);
insert into filmes (name, gender, yearr, diretores_id) values ('Client 9: The Rise and Fall of Eliot Spitzer', 'Documentary', '2021-05-08', 12);
insert into filmes (name, gender, yearr, diretores_id) values ('Foolproof', 'Action|Comedy|Crime|Thriller', '2011-11-16', 91);
insert into filmes (name, gender, yearr, diretores_id) values ('Charlie Brown Christmas, A', 'Animation|Children|Comedy', '2011-07-09', 50);
insert into filmes (name, gender, yearr, diretores_id) values ('Leading Man, The', 'Romance', '2021-02-06', 21);
insert into filmes (name, gender, yearr, diretores_id) values ('The Care Bears Adventure in Wonderland', 'Animation|Children|Comedy', '2022-07-30', 97);
insert into filmes (name, gender, yearr, diretores_id) values ('Last Emperor, The', 'Drama', '2017-01-19', 33);
insert into filmes (name, gender, yearr, diretores_id) values ('Death and the Maiden', 'Drama|Thriller', '2022-09-26', 48);
insert into filmes (name, gender, yearr, diretores_id) values ('Patty Hearst', '(no genres listed)', '2014-07-03', 13);
insert into filmes (name, gender, yearr, diretores_id) values ('10th Victim, The (La decima vittima)', 'Action|Comedy|Sci-Fi|Thriller', '2012-08-07', 40);
insert into filmes (name, gender, yearr, diretores_id) values ('Steppenwolf', 'Drama', '2018-03-11', 88);
insert into filmes (name, gender, yearr, diretores_id) values ('Pawn', 'Crime|Thriller', '2020-08-15', 83);
insert into filmes (name, gender, yearr, diretores_id) values ('Cowboy', 'Western', '2019-08-24', 65);
insert into filmes (name, gender, yearr, diretores_id) values ('Gomorrah (Gomorra)', 'Crime|Drama', '2019-09-26', 51);
insert into filmes (name, gender, yearr, diretores_id) values ('Criminal Law', 'Thriller', '2022-06-15', 18);
insert into filmes (name, gender, yearr, diretores_id) values ('Andre', 'Adventure|Children|Drama', '2017-11-06', 15);
insert into filmes (name, gender, yearr, diretores_id) values ('Identification Marks: None (Rysopis) ', 'Drama', '2017-09-08', 29);
insert into filmes (name, gender, yearr, diretores_id) values ('Cloak and Dagger', 'Drama|Romance', '2022-01-26', 2);
insert into filmes (name, gender, yearr, diretores_id) values ('Rent', 'Drama|Musical|Romance', '2014-09-02', 4);
insert into filmes (name, gender, yearr, diretores_id) values ('To Be or Not to Be', 'Comedy|Drama|War', '2012-07-26', 65);
insert into filmes (name, gender, yearr, diretores_id) values ('Vanya on 42nd Street', 'Drama', '2013-04-05', 35);
insert into filmes (name, gender, yearr, diretores_id) values ('Dragonslayer', 'Action|Adventure|Fantasy', '2016-02-03', 74);
insert into filmes (name, gender, yearr, diretores_id) values ('The Land Before Time V: The Mysterious Island', 'Adventure|Animation|Children', '2010-12-31', 49);
insert into filmes (name, gender, yearr, diretores_id) values ('Zebraman', 'Comedy', '2017-03-03', 86);
insert into filmes (name, gender, yearr, diretores_id) values ('Anchors Aweigh', 'Comedy|Musical', '2013-09-03', 91);
insert into filmes (name, gender, yearr, diretores_id) values ('100 Rifles', 'Adventure|War|Western', '2015-01-27', 56);
insert into filmes (name, gender, yearr, diretores_id) values ('Gas, Inspector Palmu! (Kaasua, komisario Palmu!)', 'Comedy|Crime|Mystery|Thriller', '2020-04-05', 38);
insert into filmes (name, gender, yearr, diretores_id) values ('Love''s Long Journey', 'Drama|Romance|Western', '2022-09-03', 60);
insert into filmes (name, gender, yearr, diretores_id) values ('She Wore a Yellow Ribbon', 'Western', '2018-02-26', 74);
insert into filmes (name, gender, yearr, diretores_id) values ('Hell and Back Again', 'Documentary|Drama|War', '2016-04-22', 7);
insert into filmes (name, gender, yearr, diretores_id) values ('Grandfather, The (Abuelo, El)', 'Drama', '2011-07-19', 74);
insert into filmes (name, gender, yearr, diretores_id) values ('Nine Lives', 'Horror|Thriller', '2019-03-12', 23);
insert into filmes (name, gender, yearr, diretores_id) values ('Forgetting the Girl', 'Drama', '2018-12-02', 84);
insert into filmes (name, gender, yearr, diretores_id) values ('One Body Too Many', 'Comedy|Horror|Mystery', '2014-05-06', 78);
insert into filmes (name, gender, yearr, diretores_id) values ('Living Desert, The', 'Documentary', '2013-08-14', 91);
insert into filmes (name, gender, yearr, diretores_id) values ('Emigrants, The (Utvandrarna)', 'Drama', '2016-01-13', 10);
insert into filmes (name, gender, yearr, diretores_id) values ('Resurrection of the Little Match Girl (Sungnyangpali sonyeoui jaerim)', 'Action|Comedy|Sci-Fi', '2016-05-09', 41);
insert into filmes (name, gender, yearr, diretores_id) values ('Last Mimzy, The', 'Adventure|Children|Sci-Fi', '2016-04-19', 94);
insert into filmes (name, gender, yearr, diretores_id) values ('Corridors of Time: The Visitors II, The (Couloirs du temps: Les visiteurs 2, Les)', 'Children|Comedy|Fantasy|Sci-Fi', '2018-07-09', 3);
insert into filmes (name, gender, yearr, diretores_id) values ('Run If You Can', 'Drama', '2013-09-27', 60);
insert into filmes (name, gender, yearr, diretores_id) values ('Defiance', 'Action|Crime|Drama', '2011-02-24', 19);
insert into filmes (name, gender, yearr, diretores_id) values ('Used Cars', 'Comedy', '2019-08-16', 96);
insert into filmes (name, gender, yearr, diretores_id) values ('Silmido', 'Action|Drama|War', '2016-04-24', 38);
insert into filmes (name, gender, yearr, diretores_id) values ('Scarecrow, The', 'Drama|Fantasy|Romance', '2015-06-05', 5);
insert into filmes (name, gender, yearr, diretores_id) values ('8 (8, the Play)', 'Drama', '2018-11-01', 7);
insert into filmes (name, gender, yearr, diretores_id) values ('Tears of the Black Tiger (Fah talai jone)', 'Action|Comedy|Romance|Western', '2015-04-09', 42);
insert into filmes (name, gender, yearr, diretores_id) values ('Executive Protection (Livvakterna)', 'Action|Thriller', '2021-06-27', 85);
insert into filmes (name, gender, yearr, diretores_id) values ('How to Lose Friends & Alienate People', 'Comedy', '2018-02-23', 2);
insert into filmes (name, gender, yearr, diretores_id) values ('Gigot', 'Comedy', '2018-01-22', 24);
insert into filmes (name, gender, yearr, diretores_id) values ('Trances', 'Documentary|Musical', '2019-06-21', 52);
insert into filmes (name, gender, yearr, diretores_id) values ('O Brother, Where Art Thou?', 'Adventure|Comedy|Crime', '2015-12-07', 43);
insert into filmes (name, gender, yearr, diretores_id) values ('Dead or Alive: Final', 'Comedy|Crime|Drama|Sci-Fi|Thriller', '2018-12-14', 52);
insert into filmes (name, gender, yearr, diretores_id) values ('Black Dog', 'Action|Thriller', '2022-04-01', 4);
insert into filmes (name, gender, yearr, diretores_id) values ('Road Games (a.k.a. Roadgames)', 'Thriller', '2011-09-12', 66);
insert into filmes (name, gender, yearr, diretores_id) values ('Big Bad Love', 'Drama', '2018-01-18', 54);
insert into filmes (name, gender, yearr, diretores_id) values ('Mitchell', 'Action|Crime', '2022-03-22', 7);
insert into filmes (name, gender, yearr, diretores_id) values ('My Flesh My Blood (Moja krew)', 'Drama', '2020-08-03', 56);
insert into filmes (name, gender, yearr, diretores_id) values ('Cake', 'Comedy|Romance', '2017-02-19', 14);
insert into filmes (name, gender, yearr, diretores_id) values ('Ashes, The (Popioly)', 'Drama|War', '2010-12-30', 59);
insert into filmes (name, gender, yearr, diretores_id) values ('Weeds', 'Drama', '2014-10-29', 11);